<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\State;
use Illuminate\Database\Seeder;

class GeoSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            'Venezuela' => [
                'Amazonas' => ['Puerto Ayacucho'],
                'Anzoategui' => ['Barcelona', 'Puerto La Cruz', 'Lecheria', 'El Tigre', 'Anaco'],
                'Apure' => ['San Fernando de Apure'],
                'Aragua' => ['Maracay', 'Turmero', 'La Victoria', 'Cagua', 'Villa de Cura'],
                'Barinas' => ['Barinas', 'Socopó'],
                'Bolivar' => ['Ciudad Bolivar', 'Puerto Ordaz', 'Ciudad Guayana', 'Upata'],
                'Carabobo' => ['Valencia', 'Naguanagua', 'San Diego', 'Guacara', 'Puerto Cabello', 'Los Guayos'],
                'Cojedes' => ['San Carlos'],
                'Delta Amacuro' => ['Tucupita'],
                'Distrito Capital' => ['Caracas'],
                'Falcon' => ['Coro', 'Punto Fijo'],
                'Guarico' => ['San Juan de los Morros', 'Calabozo', 'Valle de la Pascua'],
                'La Guaira' => ['La Guaira', 'Maiquetia', 'Catia La Mar'],
                'Lara' => ['Barquisimeto', 'Cabudare', 'Carora', 'Quibor'],
                'Merida' => ['Merida', 'El Vigia', 'Ejido', 'Tovar'],
                'Miranda' => ['Los Teques', 'Guarenas', 'Guatire', 'Charallave', 'Ocumare del Tuy', 'Petare', 'Baruta', 'Chacao', 'El Hatillo'],
                'Monagas' => ['Maturin'],
                'Nueva Esparta' => ['Porlamar', 'La Asuncion', 'Juan Griego'],
                'Portuguesa' => ['Guanare', 'Acarigua', 'Araure'],
                'Sucre' => ['Cumana', 'Carupano'],
                'Tachira' => ['San Cristobal', 'Tariba', 'Rubio'],
                'Trujillo' => ['Trujillo', 'Valera', 'Bocono'],
                'Yaracuy' => ['San Felipe', 'Chivacoa'],
                'Zulia' => ['Maracaibo', 'Cabimas', 'Ciudad Ojeda', 'San Francisco', 'Machiques', 'Santa Barbara del Zulia'],
            ],
            'Mexico' => [
                'Aguascalientes' => ['Aguascalientes'],
                'Baja California' => ['Tijuana', 'Mexicali', 'Ensenada'],
                'Baja California Sur' => ['La Paz', 'Los Cabos'],
                'Campeche' => ['Campeche'],
                'Chiapas' => ['Tuxtla Gutierrez', 'San Cristobal de las Casas'],
                'Chihuahua' => ['Chihuahua', 'Ciudad Juarez'],
                'Ciudad de Mexico' => ['Ciudad de Mexico'],
                'Coahuila' => ['Saltillo', 'Torreon', 'Monclova'],
                'Colima' => ['Colima', 'Manzanillo'],
                'Durango' => ['Durango'],
                'Estado de Mexico' => ['Toluca', 'Naucalpan', 'Ecatepec', 'Huixquilucan'],
                'Guanajuato' => ['Leon', 'Guanajuato', 'Irapuato', 'Celaya'],
                'Guerrero' => ['Acapulco', 'Chilpancingo'],
                'Hidalgo' => ['Pachuca'],
                'Jalisco' => ['Guadalajara', 'Zapopan', 'Tlaquepaque', 'Puerto Vallarta'],
                'Michoacan' => ['Morelia', 'Uruapan'],
                'Morelos' => ['Cuernavaca'],
                'Nayarit' => ['Tepic'],
                'Nuevo Leon' => ['Monterrey', 'San Pedro Garza Garcia', 'San Nicolas de los Garza', 'Apodaca'],
                'Oaxaca' => ['Oaxaca de Juarez'],
                'Puebla' => ['Puebla', 'Cholula'],
                'Queretaro' => ['Queretaro', 'San Juan del Rio'],
                'Quintana Roo' => ['Cancun', 'Playa del Carmen', 'Chetumal'],
                'San Luis Potosi' => ['San Luis Potosi'],
                'Sinaloa' => ['Culiacan', 'Mazatlan', 'Los Mochis'],
                'Sonora' => ['Hermosillo', 'Nogales', 'Ciudad Obregon'],
                'Tabasco' => ['Villahermosa'],
                'Tamaulipas' => ['Tampico', 'Reynosa', 'Matamoros'],
                'Tlaxcala' => ['Tlaxcala'],
                'Veracruz' => ['Veracruz', 'Xalapa', 'Coatzacoalcos'],
                'Yucatan' => ['Merida', 'Valladolid'],
                'Zacatecas' => ['Zacatecas'],
            ],
            'Colombia' => [
                'Amazonas' => ['Leticia'],
                'Antioquia' => ['Medellin', 'Envigado', 'Bello', 'Itagui', 'Rionegro'],
                'Atlantico' => ['Barranquilla', 'Soledad'],
                'Bolivar' => ['Cartagena'],
                'Boyaca' => ['Tunja', 'Duitama', 'Sogamoso'],
                'Caldas' => ['Manizales'],
                'Caqueta' => ['Florencia'],
                'Casanare' => ['Yopal'],
                'Cauca' => ['Popayan'],
                'Cesar' => ['Valledupar'],
                'Cordoba' => ['Monteria'],
                'Cundinamarca' => ['Bogota', 'Soacha', 'Chia', 'Zipaquira'],
                'Huila' => ['Neiva'],
                'La Guajira' => ['Riohacha'],
                'Magdalena' => ['Santa Marta'],
                'Meta' => ['Villavicencio'],
                'Narino' => ['Pasto'],
                'Norte de Santander' => ['Cucuta'],
                'Quindio' => ['Armenia'],
                'Risaralda' => ['Pereira'],
                'Santander' => ['Bucaramanga', 'Floridablanca', 'Giron'],
                'Sucre' => ['Sincelejo'],
                'Tolima' => ['Ibague'],
                'Valle del Cauca' => ['Cali', 'Palmira', 'Buenaventura'],
            ],
            'Argentina' => [
                'Buenos Aires' => ['Buenos Aires', 'La Plata', 'Mar del Plata', 'Bahia Blanca', 'Tandil'],
                'Catamarca' => ['San Fernando del Valle de Catamarca'],
                'Chaco' => ['Resistencia'],
                'Chubut' => ['Rawson', 'Comodoro Rivadavia'],
                'Cordoba' => ['Cordoba', 'Villa Carlos Paz', 'Rio Cuarto'],
                'Corrientes' => ['Corrientes'],
                'Entre Rios' => ['Parana', 'Concordia'],
                'Formosa' => ['Formosa'],
                'Jujuy' => ['San Salvador de Jujuy'],
                'La Pampa' => ['Santa Rosa'],
                'La Rioja' => ['La Rioja'],
                'Mendoza' => ['Mendoza', 'San Rafael'],
                'Misiones' => ['Posadas'],
                'Neuquen' => ['Neuquen'],
                'Rio Negro' => ['Viedma', 'San Carlos de Bariloche'],
                'Salta' => ['Salta'],
                'San Juan' => ['San Juan'],
                'San Luis' => ['San Luis'],
                'Santa Cruz' => ['Rio Gallegos'],
                'Santa Fe' => ['Rosario', 'Santa Fe'],
                'Santiago del Estero' => ['Santiago del Estero'],
                'Tierra del Fuego' => ['Ushuaia'],
                'Tucuman' => ['San Miguel de Tucuman'],
            ],
            'Chile' => [
                'Arica y Parinacota' => ['Arica'],
                'Tarapaca' => ['Iquique'],
                'Antofagasta' => ['Antofagasta', 'Calama'],
                'Atacama' => ['Copiapo'],
                'Coquimbo' => ['La Serena', 'Coquimbo'],
                'Valparaiso' => ['Valparaiso', 'Vina del Mar'],
                'Region Metropolitana' => ['Santiago', 'Providencia', 'Las Condes', 'Nunoa', 'Vitacura'],
                'OHiggins' => ['Rancagua'],
                'Maule' => ['Talca'],
                'Biobio' => ['Concepcion', 'Talcahuano'],
                'Araucania' => ['Temuco'],
                'Los Rios' => ['Valdivia'],
                'Los Lagos' => ['Puerto Montt', 'Osorno'],
                'Magallanes' => ['Punta Arenas'],
            ],
            'Peru' => [
                'Amazonas' => ['Chachapoyas'],
                'Ancash' => ['Huaraz'],
                'Arequipa' => ['Arequipa'],
                'Ayacucho' => ['Ayacucho'],
                'Cajamarca' => ['Cajamarca'],
                'Callao' => ['Callao'],
                'Cusco' => ['Cusco'],
                'Huanuco' => ['Huanuco'],
                'Ica' => ['Ica'],
                'Junin' => ['Huancayo'],
                'La Libertad' => ['Trujillo'],
                'Lambayeque' => ['Chiclayo'],
                'Lima' => ['Lima', 'Miraflores', 'San Isidro', 'Surco'],
                'Loreto' => ['Iquitos'],
                'Piura' => ['Piura'],
                'Puno' => ['Puno'],
                'San Martin' => ['Tarapoto'],
                'Tacna' => ['Tacna'],
                'Ucayali' => ['Pucallpa'],
            ],
            'Ecuador' => [
                'Azuay' => ['Cuenca'],
                'Guayas' => ['Guayaquil', 'Samborondon', 'Duran'],
                'Manabi' => ['Portoviejo', 'Manta'],
                'Pichincha' => ['Quito'],
                'Tungurahua' => ['Ambato'],
                'El Oro' => ['Machala'],
                'Loja' => ['Loja'],
                'Imbabura' => ['Ibarra'],
                'Santo Domingo' => ['Santo Domingo'],
                'Santa Elena' => ['Santa Elena', 'Salinas'],
            ],
            'Bolivia' => [
                'La Paz' => ['La Paz', 'El Alto'],
                'Cochabamba' => ['Cochabamba'],
                'Santa Cruz' => ['Santa Cruz de la Sierra'],
                'Oruro' => ['Oruro'],
                'Potosi' => ['Potosi'],
                'Sucre' => ['Sucre'],
                'Tarija' => ['Tarija'],
                'Beni' => ['Trinidad'],
                'Pando' => ['Cobija'],
            ],
            'Uruguay' => [
                'Montevideo' => ['Montevideo'],
                'Canelones' => ['Ciudad de la Costa', 'Las Piedras'],
                'Maldonado' => ['Punta del Este', 'Maldonado'],
                'Salto' => ['Salto'],
                'Colonia' => ['Colonia del Sacramento'],
                'Paysandu' => ['Paysandu'],
            ],
            'Paraguay' => [
                'Central' => ['Asuncion', 'San Lorenzo', 'Luque', 'Fernando de la Mora'],
                'Alto Parana' => ['Ciudad del Este'],
                'Itapua' => ['Encarnacion'],
                'Caaguazu' => ['Coronel Oviedo'],
            ],
            'Costa Rica' => [
                'San Jose' => ['San Jose', 'Escazu', 'Santa Ana'],
                'Alajuela' => ['Alajuela'],
                'Heredia' => ['Heredia'],
                'Cartago' => ['Cartago'],
                'Guanacaste' => ['Liberia'],
                'Puntarenas' => ['Puntarenas'],
                'Limon' => ['Limon'],
            ],
            'Panama' => [
                'Panama' => ['Ciudad de Panama', 'San Miguelito'],
                'Panama Oeste' => ['La Chorrera', 'Arraijan'],
                'Colon' => ['Colon'],
                'Chiriqui' => ['David'],
                'Cocle' => ['Penonome'],
            ],
            'Republica Dominicana' => [
                'Distrito Nacional' => ['Santo Domingo'],
                'Santiago' => ['Santiago de los Caballeros'],
                'La Altagracia' => ['Punta Cana', 'Higuey'],
                'Puerto Plata' => ['Puerto Plata'],
                'San Cristobal' => ['San Cristobal'],
            ],
            'Guatemala' => [
                'Guatemala' => ['Ciudad de Guatemala'],
                'Quetzaltenango' => ['Quetzaltenango'],
                'Escuintla' => ['Escuintla'],
                'Sacatepequez' => ['Antigua Guatemala'],
            ],
            'Honduras' => [
                'Francisco Morazan' => ['Tegucigalpa'],
                'Cortes' => ['San Pedro Sula'],
                'Atlantida' => ['La Ceiba'],
            ],
            'El Salvador' => [
                'San Salvador' => ['San Salvador', 'Santa Tecla'],
                'La Libertad' => ['Antiguo Cuscatlan'],
                'San Miguel' => ['San Miguel'],
            ],
            'Nicaragua' => [
                'Managua' => ['Managua'],
                'Leon' => ['Leon'],
                'Granada' => ['Granada'],
            ],
            'Cuba' => [
                'La Habana' => ['La Habana'],
                'Santiago de Cuba' => ['Santiago de Cuba'],
                'Camaguey' => ['Camaguey'],
            ],
            'Puerto Rico' => [
                'Puerto Rico' => ['San Juan', 'Bayamon', 'Ponce', 'Carolina'],
            ],
            'Brasil' => [
                'Sao Paulo' => ['Sao Paulo', 'Campinas', 'Santos'],
                'Rio de Janeiro' => ['Rio de Janeiro', 'Niteroi'],
                'Minas Gerais' => ['Belo Horizonte'],
                'Bahia' => ['Salvador'],
                'Parana' => ['Curitiba'],
                'Rio Grande do Sul' => ['Porto Alegre'],
                'Distrito Federal' => ['Brasilia'],
                'Pernambuco' => ['Recife'],
                'Ceara' => ['Fortaleza'],
                'Amazonas' => ['Manaus'],
            ],
        ];

        foreach ($data as $country => $states) {
            foreach ($states as $stateName => $cities) {
                $state = State::updateOrCreate(
                    ['country' => $country, 'name' => $stateName],
                );

                foreach ($cities as $cityName) {
                    City::updateOrCreate(
                        ['state_id' => $state->id, 'name' => $cityName],
                    );
                }
            }
        }
    }
}
